name: Alternate Validate sample queries
on:
  workflow_dispatch:
  push:
    branches:
      - jasonjoh/json-validation

jobs:
  validate-json-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Validate JSON schema
        uses: walbo/validate-json@v1.1.0
        with:
          schema: /tests/samples.schema.json
          files: /sample-queries/sample-queries.json

  test:
    runs-on: ubuntu-latest
    needs: validate-json-schema
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: Run test
        run: npm run test
