name: Alternate Validate sample queries
on:
  workflow_dispatch:
  push:
    branches:
      - jasonjoh/json-validation

jobs:
  validate-json-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Validate JSON schema
        uses: dsanders11/json-schema-validate-action@v1.4.0
        with:
          schema: tests/samples.schema.json
          files: sample-queries/sample-queries.json
